[tool.poetry]
name = "egsnrc2py"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
typing-extensions = "*"
jax = "*"
jaxlib = "*"
matplotlib = "*"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
mypy = "*"
rope = "*"
pylint = "*"
pytest = "*"
